// <auto-generated />
using System;
using ItauInvestmentBroker.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItauInvestmentBroker.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306014922_InitialSchemaWithBusinessConstraints")]
    partial class InitialSchemaWithBusinessConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.Cesta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int?>("AtivaUnica")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("ativa_unica")
                        .HasComputedColumnSql("CASE WHEN `Ativa` = 1 THEN 1 ELSE NULL END", true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AtivaUnica")
                        .IsUnique();

                    b.ToTable("cestas", (string)null);
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataAdesao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.ContaGrafica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.HasIndex("NumeroConta")
                        .IsUnique();

                    b.ToTable("contas_graficas", (string)null);
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.Custodia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ContaGraficaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ContaGraficaId");

                    b.ToTable("custodias", (string)null);
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.Distribuicao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataDistribuicao")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("OrdemCompraId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("OrdemCompraId");

                    b.ToTable("distribuicoes", (string)null);
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.HistoricoValorMensal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ValorAnterior")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorNovo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("historico_valor_mensal", (string)null);
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.ItemCesta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CestaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Percentual")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CestaId");

                    b.ToTable("itens_cesta", (string)null);
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.ItemDistribuicao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ContaGraficaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("DistribuicaoId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ContaGraficaId");

                    b.HasIndex("DistribuicaoId");

                    b.ToTable("itens_distribuicao", (string)null);
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.ItemOrdemCompra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("OrdemCompraId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("TipoMercado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrdemCompraId");

                    b.ToTable("itens_ordem_compra", (string)null);
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.OrdemCompra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CestaId")
                        .HasColumnType("bigint");

                    b.Property<long>("ContaGraficaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CestaId");

                    b.HasIndex("ContaGraficaId");

                    b.ToTable("ordens_compra", (string)null);
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.VendaRebalanceamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Lucro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ValorVenda")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "DataVenda");

                    b.ToTable("vendas_rebalanceamento", (string)null);
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.ContaGrafica", b =>
                {
                    b.HasOne("ItauInvestmentBroker.Domain.Entities.Cliente", "Cliente")
                        .WithOne("ContaGrafica")
                        .HasForeignKey("ItauInvestmentBroker.Domain.Entities.ContaGrafica", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.Custodia", b =>
                {
                    b.HasOne("ItauInvestmentBroker.Domain.Entities.ContaGrafica", "ContaGrafica")
                        .WithMany("Custodias")
                        .HasForeignKey("ContaGraficaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaGrafica");
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.Distribuicao", b =>
                {
                    b.HasOne("ItauInvestmentBroker.Domain.Entities.OrdemCompra", "OrdemCompra")
                        .WithMany()
                        .HasForeignKey("OrdemCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdemCompra");
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.HistoricoValorMensal", b =>
                {
                    b.HasOne("ItauInvestmentBroker.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.ItemCesta", b =>
                {
                    b.HasOne("ItauInvestmentBroker.Domain.Entities.Cesta", "Cesta")
                        .WithMany("Itens")
                        .HasForeignKey("CestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cesta");
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.ItemDistribuicao", b =>
                {
                    b.HasOne("ItauInvestmentBroker.Domain.Entities.ContaGrafica", "ContaGrafica")
                        .WithMany()
                        .HasForeignKey("ContaGraficaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItauInvestmentBroker.Domain.Entities.Distribuicao", "Distribuicao")
                        .WithMany("Itens")
                        .HasForeignKey("DistribuicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaGrafica");

                    b.Navigation("Distribuicao");
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.ItemOrdemCompra", b =>
                {
                    b.HasOne("ItauInvestmentBroker.Domain.Entities.OrdemCompra", "OrdemCompra")
                        .WithMany("Itens")
                        .HasForeignKey("OrdemCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdemCompra");
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.OrdemCompra", b =>
                {
                    b.HasOne("ItauInvestmentBroker.Domain.Entities.Cesta", "Cesta")
                        .WithMany()
                        .HasForeignKey("CestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItauInvestmentBroker.Domain.Entities.ContaGrafica", "ContaGrafica")
                        .WithMany("OrdensCompra")
                        .HasForeignKey("ContaGraficaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cesta");

                    b.Navigation("ContaGrafica");
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.VendaRebalanceamento", b =>
                {
                    b.HasOne("ItauInvestmentBroker.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.Cesta", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("ContaGrafica");
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.ContaGrafica", b =>
                {
                    b.Navigation("Custodias");

                    b.Navigation("OrdensCompra");
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.Distribuicao", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ItauInvestmentBroker.Domain.Entities.OrdemCompra", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
